cabal-version: 3.0
name:          case-accelerate
version:       0.1.0
license:       BSD-3-Clause
license-file:  LICENSE
author:        Edsko de Vries
maintainer:    edsko@well-typed.com
build-type:    Simple

common lang
  build-depends:    base >= 4.21 && < 5
  default-language: GHC2024

  ghc-options:
      -Wall
      -Wprepositive-qualified-module
      -Wredundant-constraints
      -Wunused-packages

  default-extensions:
      DuplicateRecordFields
      LambdaCase
      OverloadedRecordDot
      OverloadedStrings
      QuantifiedConstraints

library
  import:          lang
  hs-source-dirs:  src
  build-depends:   containers, mtl
  exposed-modules: MiniAccelerate

executable case-accelerate
  import:         lang
  main-is:        Main.hs
  hs-source-dirs: app
  build-depends:  case-accelerate
  other-modules:  Testcases



